#!/bin/bash

xfsettingsd &
xfce4-power-manager &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

if pgrep picom &> /dev/null ; then pkill picom ; fi
picom -b

.config/polybar/launch.sh

setxkbmap -layout it
setxkbmap -option caps:super

nitrogen --restore

pulseaudio --start

dunst &

flameshot &
