#!/bin/bash

xfsettingsd &
xfce4-power-manager &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon
.config/polybar/launch.sh

pkill picom
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom -b


setxkbmap -layout us
setxkbmap -option caps:hyper
xmodmap ~/.Xmodmap
#sudo xkeysnail ~/.config/xkeysnail/config.py --watch -q & 

nitrogen --restore

pulseaudio --start

dunst &

flameshot &
