#!/bin/bash

#
# Keybinding Portion of HLWM config
#

# Function to make commands less annoying
hc() {
    herbstclient "$@"
}


TERMINAL=alacritty

# remove all existing keybindings
hc keyunbind --all

# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4 

# basic action
hc keybind $Mod-Shift-q close
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-e quit

# terminals
hc keybind $Mod-Return spawn "${TERMINAL:-xterm}"
hc keybind $Mod-Shift-Return spawn "${TERMINAL:-xterm}" --class floating_term,floating_term
hc keybind $Mod-Ctrl-Return spawn "${TERMINAL:-xterm}" --class teeny_term,teeny_term

# focusing clients
hc keybind $Mod-Left     focus left
hc keybind $Mod-Down     focus down
hc keybind $Mod-Up     focus up
hc keybind $Mod-Right     focus right

# focus
hc keybind $Mod-c cycle
hc keybind $Mod-Shift-c cycle -1
hc keybind $Mod-i jumpto urgent

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left     shift left
hc keybind $Mod-Shift-Down     shift down
hc keybind $Mod-Shift-Up     shift up
hc keybind $Mod-Shift-Right     shift right

# create an empty frame at the specified direction
hc keybind $Mod-Ctrl-Down spawn ~/.config/herbstluftwm/scripts/split bottom
hc keybind $Mod-Ctrl-Left spawn ~/.config/herbstluftwm/scripts/split left
hc keybind $Mod-Ctrl-Up spawn ~/.config/herbstluftwm/scripts/split top
hc keybind $Mod-Ctrl-Right spawn ~/.config/herbstluftwm/scripts/split right

# selecting split ratio
echo 0.5 > ~/.config/herbstluftwm/ratio
for boomer in {1..9}; do
    hc keybind $Mod-Ctrl-$boomer spawn ~/.config/herbstluftwm/scripts/ratioset "0.$boomer"
done

# frame invisibility toggle
hc keybind $Mod-v set frame_bg_transparent toggle


# let the current frame explode into subframes
hc keybind $Mod-Ctrl-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Alt-Left       resize left +$resizestep
hc keybind $Mod-Alt-Down       resize down +$resizestep
hc keybind $Mod-Alt-Up       resize up +$resizestep
hc keybind $Mod-Alt-Right       resize right +$resizestep

# tags
tag_names=( "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X")
tag_keys=( {1..9} 0 )

# hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-s set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-p pseudotile toggle

# restore all minimized windows of the focused tag
hc keybind $Mod-Ctrl-m foreach CLIENT clients. \
     sprintf MINATT "%c.minimized" CLIENT \
     sprintf TAGATT "%c.tag" CLIENT and \
       , compare MINATT "=" "true" \
       , substitute FOCUS "tags.focus.name" compare TAGATT "=" FOCUS \
       , set_attr MINATT false

# The following cycles through the available layouts within a frame
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# night mode
hc keybind $Mod-Ctrl-r spawn ~/.config/herbstluftwm/scripts/nightmode

# rofi bs
hc keybind $Mod-d spawn rofi -show drun -Rightocation 1 -xoffset 20 -yoffset 20 -columns 1 -width 10 -Rightines 5
hc keybind $Mod-w spawn rofi -show window -Rightocation 1 -xoffset 20 -yoffset 20 -width 18 -Rightines 5
hc keybind $Mod-m spawn ~/.config/herbstluftwm/scripts/mpc_rof
hc keybind $Mod-b spawn ~/.config/herbstluftwm/scripts/bctl
hc keybind $Mod-t spawn ~/.config/herbstluftwm/scripts/tmxui
hc keybind $Mod-Shift-p spawn ~/.config/herbstluftwm/scripts/power

# screenshots
hc keybind Print spawn scrot -e 'mv $f ~/Pictures/Screenshots'
hc keybind $Mod-Print spawn scrot -u -b -e 'mv $f ~/Pictures/Screenshots'
hc keybind $Mod-Ctrl-Print spawn flameshot gui



hc keybind $Mod-n spawn notion-app-nativefier

hc keybind $Mod-Ctrl-p spawn pavucontrol

hc keybind $Mod-e spawn emacs

# EWW launcher
hc keybind $Mod-Shift-d spawn ~/.config/herbstluftwm/scripts/launcher
