#!/bin/bash@
# Setup Portion of HLWM config
#

# Function to make commands less annoying
hc() {
    herbstclient "$@"
}

hc detect_monitors
hc set_attr monitors.0.pad_up 63

hc emit_hook reload

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floatplacement=center
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class="floating_term" floating=on floatplacement=center
hc rule class="feh" floating=on floatplacement=center
hc rule class="Pavucontrol" floating=on floatplacement=center
hc rule class="floating_term" floating=on floatplacement=center
hc rule class="teeny_term" floating=on floatplacement=center
hc rule title="launcher" floating=on floatplacement=center
hc set tree_style '╾│ ├└╼─┐'
hc set focus_follows_mouse true
# unlock, just to be sure
hc unlock
