[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-miramare
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-miramare
GtkTheme=oomox-miramare
IconTheme=oomox-miramare
MetacityTheme=oomox-miramare
